controller:
  image:
    repository: jenkins/jenkins
    tag: lts
    pullPolicy: Always
  serviceType: ClusterIP

persistence:
  enabled: true
  existingClaim: ""
  storageClass: ebs-sc
  size: 20Gi

# Resource requests for the controller; you can adjust if nodes are small
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

rbac:
  create: true

serviceAccount:
  create: true
